### ISSUE TITLE
Orientation Not working on IOS

### ISSUE THREAD

**Issue by PixsaOJ** [vallemar/NativeScriptVueUse#11]
```
 ***** Fatal JavaScript exception - application has been terminated. *****
  NativeScript encountered a fatal error:
  Uncaught TypeError: Cannot read properties of undefined (reading 'ios')
   at
        updateiOSLockScreen(file: app/webpack:/_/node_modules/.pnpm/@nativescript-use+nativescript-orientation@0.0.3/node_modules/@nativescript-use/nativescript-orientation/index.ios.js:98:23)
        at disableRotation(file: app/webpack:/_/node_modules/.pnpm/@nativescript-use+nativescript-orientation@0.0.3/node_modules/@nativescript-use/nativescript-orientation/index.ios.js:42:0)
        
       
```

versions:
"@nativescript/ios": "8.6.2",
"nativescript-vue": "~2.9.3",

**Comment by vallemar** [comment]
Hello @PixsaOJ.
Can you tell me what NS flavor you are in (vue, angular, svelte, js...)? Also, can you also send me which package you are using (`@nativescript-use/nativescript-orientation` or `@nativescript-use/vue`)?

Thanks for reporting!

**Comment by PixsaOJ** [comment]
Hi, I am only using `nativescript-vue` not `@nativescript-use/vue`. This means I use Vue flavor. 
Yes  I am using `@nativescript-use/nativescript-orientation` this is the correct repository for this package isn't it?

**Comment by vallemar** [comment]
Yes, this is the correct one.
Taking a look I think I know what it could be, you are doing `.enableRotation()` or `.disableRotation()` at the start of your application or in your main component, right?

If so try this:
```ts
import { onApplicationMounted, useScreenOrientation } from '@nativescript-use/vue';

const {
   orientation,
   setOrientation,
   enableRotation,
   disableRotation
} = useScreenOrientation()

onApplicationMounted(() => {
     setOrientation("your_orientation");
     //or
     enableRotation();
     //or
     disableRotation();
})
```
Depending on which ones you are using

**Comment by PixsaOJ** [comment]
```
  ***** Fatal JavaScript exception - application has been terminated. *****
  NativeScript encountered a fatal error:
  Error calling module function
  TypeError: (0 , nativescript_vue__WEBPACK_IMPORTED_MODULE_0__.effectScope) is not a function
  File: (file: app/webpack:/_/node_modules/.pnpm/@nativescript-use+vue@0.0.26/node_modules/@nativescript-use/vue/src/globalState.js:5:29)
  StackTrace:
        createGlobalState(file: app/webpack:/_/node_modules/.pnpm/@nativescript-use+vue@0.0.26/node_modules/@nativescript-use/vue/src/globalState.js:5:29)
        at ./node_modules/.pnpm/@nativescript-use+vue@0.0.26/node_modules/@nativescript-use/vue/src/useColorMode/index.js(file: app/webpack:/cnick/node_modules/.pnpm/@nativescript-use+vue@0.0.26/node_modules/@nativescript-use/vue/src/useColorMode/index.js:7:40)
        at __webpack_require__(file: app/webpack:/cnick/webpack/bootstrap:19:0)
        at ./node_modules/.pnpm/@nativescript-use+vue@0.0.26/node_modules/@nativescript-use/vue/index.js(file:///app/vendor.js:49817:75)
        at __webpack_require__(file: app/webpack:/cnick/webpack/bootstrap:19:0)
```

This is what i am getting now. I also tried mounted hook, same error

**Comment by vallemar** [comment]
Now it seems to fail because of `useColorMode`. Can you send me a message about how you are using this function?

**Comment by vallemar** [comment]
@PixsaOJ ohhhh, I just saw that you are using vue2. This library is intended for NS-vue 3!

**Comment by PixsaOJ** [comment]
I don't use 3 because its in beta.

So can't i just use `@nativescript-use/nativescript-orientation` itself?

**Comment by vallemar** [comment]
Yeah! You can use `@nativescript-use/nativescript-orientation`, it is intended to be used from all flavors, but you must take into account that the application is mounted, for that do:

```ts
import { Orientation } from "@nativescript-use/nativescript-orientation"
import { Application } from '@nativescript/core';

const orientation = new Orientation();

Application.on('launch', () =>{
      orientation.disableRotation();
})
```

Note: I have applications in production with ns-vue3. Although it is in beta, its state is quite advanced and it can do everything

**Comment by PixsaOJ** [comment]
Okay, so `Application.on('launch',` did not work, because event probably already happened.

But, when I moved my code to `mounted()` hook, everything has fixed.

just use:

```Js
import { Orientation } from "@nativescript-use/nativescript-orientation";


mounted() {
 orientation.setOrientation("portrait");
 orientation.disableRotation();
 // ...
}
```

Thanks for help!

**Comment by vallemar** [comment]
Just as a note, add a section in the vue docs for this https://nativescriptuse-vue.netlify.app/src/useScreenOrientation/#usage-in-app-ts-or-maincomponent-vue

**Comment by PixsaOJ** [comment]
I guess `MainComponent.vue ` suggestion could be wrong. Launch hook could be already gone depending on configuration. It will be good to tell people they might need to use `mounted()` hook.
